# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
    build:
        docker:
            # specify the version
            - image: buildpack-deps:bionic-scm

        working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
        branches:
            only:
                - master
        steps:
            - checkout
            # specify any bash command here prefixed with `run: `
            - run: wget https://github.com/mah0x211/mixdown/releases/download/master/mixdown-linux.tar.gz
            - run: tar -zxvf ./mixdown-linux.tar.gz
            - run: ./mixdown -outdir /tmp/mixdown-docs
            - run: git config --global user.email "$GIT_AUTHOR_EMAIL"
            - run: git config --global user.name "$GIT_AUTHOR_NAME"
            - run: git checkout gh-pages 2>/dev/null || git checkout -b gh-pages
            - run: mkdir /tmp/trash && mv ./* /tmp/trash/
            - run: git ls-files | xargs git rm -f --ignore-unmatch
            - run: mv /tmp/mixdown-docs/* .
            - run: git add . && git status
            - run: git diff-index --quiet HEAD || git commit -m "Build at $(date -R)"
            - run: git push origin HEAD
